name: coalition_app_v2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_riverpod: ^3.0.0
  wechat_assets_picker: ^9.2.0
  video_player: ^2.9.1
  video_editor_2: ^1.0.8
  background_downloader: ^9.0.5
  http: ^1.2.2
  uuid: ^4.4.2
  infinite_scroll_pagination: ^5.0.0

flutter:
  uses-material-design: true
