name: coalition_app_v2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.4
  flutter_riverpod: ^3.0.0
  wechat_assets_picker: ^9.2.0
  permission_handler: ^11.3.1
  video_player: ^2.9.1
  video_editor_2: ^3.1.1
  background_downloader: ^9.0.5
  http: ^1.2.2
  http_parser: ^4.0.2
  uuid: ^4.4.2
  infinite_scroll_pagination: ^5.0.0
  device_info_plus: ^10.1.0
  dio: ^5.9.0
  path_provider: ^2.1.3
  amplify_flutter: ^2.6.0
  amplify_auth_cognito: ^2.6.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.3.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
