/// The Amplify configuration generated by the Amplify CLI.
///
/// Replace the placeholder values below with the real configuration output
/// from `amplify pull` or `amplify init`. Keeping the structure in a dedicated
/// file allows us to avoid checking in platform-specific JSON assets.
const String amplifyconfig = '''
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/2.0",
        "Version": "1.0"
      }
    }
  }
}
''';
